[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "calan"
dynamic = ["version"]
authors = [
    {name = "Nick Ackerley", email = "nicholas.ackerley@nrcan-rncan.gc.ca"},
]
description = "Tools for relative (electrical) calibration of seismic instrumentation."
readme = "README.md"
requires-python = ">=3.8, <4"
dependencies = [
    "numpy",
    "pandas",
    "obspy",
    "timezonefinder",
    "statsmodels",
    "urllib3",
    "pytz",
]

[project.optional-dependencies]
develop = [
    "pylint",
    "flake8",
    "pydocstyle",
    "mypy",
    "types-python-dateutil",
    "types-pytz",
    "pandas-stubs",
    "pytest",
    "pytest-cov",
]

[project.scripts]
sine_analyzer = "calan.sine_analyzer:main"
arbitrary_analyzer = "calan.arbitrary_analyzer:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.mypy]
files = "src"
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
    "matplotlib",
    "scipy.*",
    "obspy.*",
    "statsmodels.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "calan.arbitrary_analyzer",
    "calan.fit_response",
    "calan.stft",
]
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.pydocstyle]
match_dir = "src"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
# omit coverage options to debug tests in VSCode
# e.g. addopts = "--durations=0 --ignore=deprecated_tools"
addopts = "--durations=0 --ignore=deprecated_tools --cov=src --cov-report term --cov-report xml:coverage.xml --cov-config=.coveragerc"
